### ISSUE TITLE
compile issues

### ISSUE THREAD

**Issue by developerMonkey** [YellowAndGreen/Yolov5-OpenCV-Cpp-Python-ROS#1]
Yolov5-OpenCV-Cpp-Python-ROS/Yolo_ROS/ros.cpp:51:55: error: too few arguments to function ‘std::vector<std::__cxx11::basic_string<char> > load_class_list(std::string&)’
   51 | std::vector<std::string> class_list = load_class_list();
      |                                                       ^

**Comment by YellowAndGreen** [comment]
Function load_class_list() loads the class name from a txt file and this happened in the main function.
I think the easiest way to solve this is: delete the `load_class_list();`, namely, leave the declaration alone:
```
std::vectorstd::string class_list;
```
