### ISSUE TITLE
无法找到OpenCVConfig.cmake

### ISSUE THREAD

**Issue by HDLai** [YellowAndGreen/Yolov5-OpenCV-Cpp-Python-ROS#2]
![image](https://user-images.githubusercontent.com/46241502/217463562-8ff0f8c5-0a69-493a-9157-22379e1931fd.png)
这是为啥呢？
opencv是4.7.0版本

**Comment by YellowAndGreen** [comment]
没有找到opencv，应该是需要修改cmakelists中的opencv路径到实际的路径，这里写的是我自己电脑的opencv路径。
