### ISSUE TITLE
ROS Noetic Support? (Segmentation fault)

### ISSUE THREAD

**Issue by ImamWahyuda** [YellowAndGreen/Yolov5-OpenCV-Cpp-Python-ROS#3]
When i use ROS Noetic, i'm facing segmentation fault though i just use the source of original code https://github.com/doleron/yolov5-opencv-cpp-python
Is there any help by using ROS Noetic with this code?

**Comment by YellowAndGreen** [comment]
I'm sorry that this code wasn't tested in  **ROS Noetic** environment, thus the communication bewteen ROS and openCV should be reconsidered, namely, the code of  ROS and the version of cv_bridge should be adapted to support ROS Noetic.

**Comment by ImamWahyuda** [comment]
Thank you for the response, i think ROS version is doesn't matter for handle image but problem happens. Will be digging for the ROS Noetic compabilities
